name: Playwright Tests

on: [push, pull_request]

permissions:
  contents: read

jobs:
  playwright_tests:
    name: Playwright End-to-end UI Test
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: unopim
        ports:
          - 3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: curl, fileinfo, gd, intl, mbstring, openssl, pdo, pdo_mysql, tokenizer, zip
          ini-values: error_reporting=E_ALL
          tools: composer:v2

      - name: Install UnoPim & link DAM
        run: |
          composer create-project unopim/unopim unopim-core --no-interaction --no-progress
          cd unopim-core
          composer config repositories.dam '{"type": "path", "url": "../"}'
          composer require unopim/dam:@dev --no-interaction --no-progress

      - name: Setup environment
        run: |
          cd unopim-core
          cp .env.example .env
          sed -i "s|^\(APP_ENV=\s*\).*$|\1testing|" .env
          sed -i "s|^\(DB_HOST=\s*\).*$|\1127.0.0.1|" .env
          sed -i "s|^\(DB_PORT=\s*\).*$|\1${{ job.services.mysql.ports['3306'] }}|" .env
          sed -i "s|^\(DB_DATABASE=\s*\).*$|\1unopim|" .env
          sed -i "s|^\(DB_USERNAME=\s*\).*$|\1root|" .env
          sed -i "s|^\(DB_PASSWORD=\s*\).*$|\1root|" .env
          cat .env

      - name: Run UnoPim Installer
        run: |
          cd unopim-core
          php artisan unopim:install --skip-env-check --skip-admin-creation
          php artisan unopim-dam:install --skip-env-check
          php artisan migrate:fresh --seed
          php artisan serve --host=0.0.0.0 --port=8000 &

      - name: Wait for UnoPim to start
        run: npx wait-on http://localhost:8000

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Playwright dependencies
        run: |
          cd tests/e2e-pw
          npm install
          npx playwright install-deps chromium
          npx playwright install chromium

      - name: Run Playwright tests
        run: |
          cd tests/e2e-pw
          npx playwright test --reporter=list

      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: tests/e2e-pw/playwright-report
