name: UnoPim + DAM Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: unopim
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 -uroot -proot"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, bcmath, pdo, pdo_mysql, curl, intl, gd
          coverage: none

      - name: Install Composer dependencies
        working-directory: packages/Webkul/unopim
        run: composer install --no-interaction --prefer-dist --no-scripts

      - name: Create .env file
        working-directory: packages/Webkul/unopim
        run: |
          cat <<EOT > .env
APP_NAME=UnoPim
APP_ENV=testing
APP_KEY=
APP_DEBUG=true
APP_URL=http://127.0.0.1:8000

DB_CONNECTION=mysql
DB_HOST=127.0.0.1
DB_PORT=3306
DB_DATABASE=unopim
DB_USERNAME=root
DB_PASSWORD=root

CACHE_DRIVER=file
SESSION_DRIVER=file
QUEUE_CONNECTION=sync
EOT
          cat .env

      - name: Generate app key & migrate DB
        working-directory: packages/Webkul/unopim
        run: |
          php artisan key:generate
          php artisan migrate:fresh --seed

      - name: Install DAM module
        working-directory: packages/Webkul/unopim
        run: |
          composer require unopim/dam --no-interaction
          php artisan migrate --path=packages/DAM/database/migrations

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Playwright dependencies
        run: |
          npx playwright install-deps chromium
          npx playwright install chromium

      - name: Install npm dependencies
        working-directory: packages/Webkul/unopim
        run: npm install

      - name: Run Playwright tests
        working-directory: packages/Webkul/unopim
        run: npx playwright test --reporter=html
